### ISSUE TITLE
Weird Tiberium Grid Bug

### ISSUE THREAD

**Issue by Waldleufer** [RealTelefonmast/OfficialTiberiumRim#13] opened 2022-02-08 09:27 UTC
### **Describe the bug**
  
The Tiberium Grid shows a strict line between two sections where the radiation should be about the same.

### **Describe your game setup**
  
1. - I installed TiberiumRim and then created a fresh colony
2. - Running other Mods besides TiberimRim, HugsLib and Harmony  
3. Playing with the following **DLCs enabled** 
   - Rimworld - **Royalty**
   - Rimworld - **Ideology**

### **To Reproduce**
Steps to reproduce the behaviour:
Play a colony for a while with the Tiberium out of the regular viewed area on a fairly big map. Observe the glitch in the matrix.

### **HugsLib Errorlog** 
https://gist.github.com/719bb4f4040fc6c169e38194f0f7cb8f

### **Expected behavior**
- [ ] The grid should show the expected radiation levels at every cell

### **Actual behavior**
It shows random "blue"-radiation levels (Which is a very high radiation I suppose?)

### **Screenshots**
![image](https://user-images.githubusercontent.com/22003632/152957081-d4a60fda-eedb-4475-85a7-97a68b718374.png)

**Comment by RealTelefonmast** [comment] 2022-03-18 16:32
Issue was seemingly caused by saving and loading the grid even though it already gets set by tiberium simply spawning, however, why it does so only in the lower quarter of the map is strange. Either way, it is fixed now.

**Closed by RealTelefonmast** 2022-03-18 16:32 UTC
Labels: bug
